table: logic_table.cpp
	gcc logic_table.cpp -o logic_table -lstdc++
table_exec:
	./logic_table
list: table_management.cpp
	gcc table_management.cpp -o table_management -lstdc++ 
list_exec:
	./table_management
clean:
	rm -f *.o logic_table table_management